spring.application.name=banking

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=regnology
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.sql.init.data-locations=data.sql //this is bydefault the same

